// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
)

type Challenge struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Difficulty  int64  `json:"difficulty"`
	TestCount   int64  `json:"test_count"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type ChallengeTest struct {
	ID             int64  `json:"id"`
	ChallengeID    int64  `json:"challenge_id"`
	InputData      string `json:"input_data"`
	ExpectedOutput string `json:"expected_output"`
	CreatedAt      int64  `json:"created_at"`
}

type Solution struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	ChallengeID int64          `json:"challenge_id"`
	Code        string         `json:"code"`
	Language    string         `json:"language"`
	Status      string         `json:"status"`
	RuntimeInfo sql.NullString `json:"runtime_info"`
	CreatedAt   int64          `json:"created_at"`
}

type User struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserCompletedChallenge struct {
	UserID         int64         `json:"user_id"`
	ChallengeID    int64         `json:"challenge_id"`
	CompletedAt    int64         `json:"completed_at"`
	BestSolutionID sql.NullInt64 `json:"best_solution_id"`
}
