// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package data

import (
	"context"
	"database/sql"
)

const countChallenges = `-- name: CountChallenges :one
SELECT COUNT(*) AS count FROM challenges
`

func (q *Queries) CountChallenges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChallenges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, title, description, difficulty, test_count, created_at, updated_at FROM challenges
WHERE id = ?
`

func (q *Queries) GetChallenge(ctx context.Context, id int64) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, getChallenge, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.TestCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallenges = `-- name: GetChallenges :many
SELECT id, title, description, difficulty, test_count, created_at, updated_at FROM challenges
ORDER BY created_at DESC
`

func (q *Queries) GetChallenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, getChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.TestCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChallengesPaginated = `-- name: GetChallengesPaginated :many
SELECT id, title, description, difficulty, test_count, created_at, updated_at FROM challenges
ORDER BY
	  test_count DESC
LIMIT ? OFFSET ?
`

func (q *Queries) GetChallengesPaginated(ctx context.Context, limit int64, offset int64) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, getChallengesPaginated, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.TestCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedChallengesForUser = `-- name: GetCompletedChallengesForUser :many
SELECT user_id, challenge_id, completed_at, best_solution_id FROM user_completed_challenges
WHERE user_id = ?
ORDER BY completed_at DESC
`

func (q *Queries) GetCompletedChallengesForUser(ctx context.Context, userID int64) ([]UserCompletedChallenge, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedChallengesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCompletedChallenge
	for rows.Next() {
		var i UserCompletedChallenge
		if err := rows.Scan(
			&i.UserID,
			&i.ChallengeID,
			&i.CompletedAt,
			&i.BestSolutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSolutionsForChallenge = `-- name: GetSolutionsForChallenge :many
SELECT id, user_id, challenge_id, code, language, status, runtime_info, created_at FROM solutions
WHERE challenge_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetSolutionsForChallenge(ctx context.Context, challengeID int64) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutionsForChallenge, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.Code,
			&i.Language,
			&i.Status,
			&i.RuntimeInfo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestDataForChallenge = `-- name: GetTestDataForChallenge :many
SELECT input_data as input, expected_output as output
FROM challenge_tests
WHERE challenge_id = ?
ORDER BY length(input_data) ASC
`

type GetTestDataForChallengeRow struct {
	Input  string `json:"input"`
	Output string `json:"output"`
}

func (q *Queries) GetTestDataForChallenge(ctx context.Context, challengeID int64) ([]GetTestDataForChallengeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTestDataForChallenge, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTestDataForChallengeRow
	for rows.Next() {
		var i GetTestDataForChallengeRow
		if err := rows.Scan(&i.Input, &i.Output); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestsForChallenge = `-- name: GetTestsForChallenge :many
SELECT id, challenge_id, input_data, expected_output, created_at FROM challenge_tests
WHERE challenge_id = ?
ORDER BY id
`

func (q *Queries) GetTestsForChallenge(ctx context.Context, challengeID int64) ([]ChallengeTest, error) {
	rows, err := q.db.QueryContext(ctx, getTestsForChallenge, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeTest
	for rows.Next() {
		var i ChallengeTest
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.InputData,
			&i.ExpectedOutput,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, is_admin, created_at, updated_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, username, password_hash, is_admin, created_at, updated_at FROM users
WHERE username = ?
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCompletedChallengesWithDetails = `-- name: GetUserCompletedChallengesWithDetails :many
SELECT 
    c.id as challenge_id,
    c.title,
    c.difficulty,
    c.test_count,
    ucc.completed_at,
    s.language,
    s.runtime_info,
    s.created_at as solution_created_at
FROM user_completed_challenges ucc
JOIN challenges c ON ucc.challenge_id = c.id
LEFT JOIN solutions s ON ucc.best_solution_id = s.id
JOIN users u ON ucc.user_id = u.id
WHERE u.username = ?
ORDER BY ucc.completed_at DESC
`

type GetUserCompletedChallengesWithDetailsRow struct {
	ChallengeID       int64          `json:"challenge_id"`
	Title             string         `json:"title"`
	Difficulty        int64          `json:"difficulty"`
	TestCount         int64          `json:"test_count"`
	CompletedAt       int64          `json:"completed_at"`
	Language          string         `json:"language"`
	RuntimeInfo       sql.NullString `json:"runtime_info"`
	SolutionCreatedAt int64          `json:"solution_created_at"`
}

func (q *Queries) GetUserCompletedChallengesWithDetails(ctx context.Context, username string) ([]GetUserCompletedChallengesWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCompletedChallengesWithDetails, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCompletedChallengesWithDetailsRow
	for rows.Next() {
		var i GetUserCompletedChallengesWithDetailsRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.Title,
			&i.Difficulty,
			&i.TestCount,
			&i.CompletedAt,
			&i.Language,
			&i.RuntimeInfo,
			&i.SolutionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDifficultyBreakdown = `-- name: GetUserDifficultyBreakdown :many
SELECT 
    c.difficulty,
    COUNT(DISTINCT ucc.challenge_id) as completed_count
FROM user_completed_challenges ucc
JOIN challenges c ON ucc.challenge_id = c.id
JOIN users u ON ucc.user_id = u.id
WHERE u.username = ?
GROUP BY c.difficulty
ORDER BY c.difficulty
`

type GetUserDifficultyBreakdownRow struct {
	Difficulty     int64 `json:"difficulty"`
	CompletedCount int64 `json:"completed_count"`
}

func (q *Queries) GetUserDifficultyBreakdown(ctx context.Context, username string) ([]GetUserDifficultyBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserDifficultyBreakdown, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDifficultyBreakdownRow
	for rows.Next() {
		var i GetUserDifficultyBreakdownRow
		if err := rows.Scan(&i.Difficulty, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLanguageStats = `-- name: GetUserLanguageStats :many
SELECT 
    s.language,
    COUNT(*) as submission_count,
    COUNT(CASE WHEN s.status = 'accepted' THEN 1 END) as accepted_count
FROM solutions s
JOIN users u ON s.user_id = u.id
WHERE u.username = ?
GROUP BY s.language
ORDER BY submission_count DESC
`

type GetUserLanguageStatsRow struct {
	Language        string `json:"language"`
	SubmissionCount int64  `json:"submission_count"`
	AcceptedCount   int64  `json:"accepted_count"`
}

func (q *Queries) GetUserLanguageStats(ctx context.Context, username string) ([]GetUserLanguageStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserLanguageStats, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLanguageStatsRow
	for rows.Next() {
		var i GetUserLanguageStatsRow
		if err := rows.Scan(&i.Language, &i.SubmissionCount, &i.AcceptedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentSubmissions = `-- name: GetUserRecentSubmissions :many
SELECT 
    s.id,
    s.challenge_id,
    c.title as challenge_title,
    s.language,
    s.status,
    s.runtime_info,
    s.created_at
FROM solutions s
JOIN challenges c ON s.challenge_id = c.id
JOIN users u ON s.user_id = u.id
WHERE u.username = ?
ORDER BY s.created_at DESC
LIMIT ?
`

type GetUserRecentSubmissionsRow struct {
	ID             int64          `json:"id"`
	ChallengeID    int64          `json:"challenge_id"`
	ChallengeTitle string         `json:"challenge_title"`
	Language       string         `json:"language"`
	Status         string         `json:"status"`
	RuntimeInfo    sql.NullString `json:"runtime_info"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) GetUserRecentSubmissions(ctx context.Context, username string, limit int64) ([]GetUserRecentSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecentSubmissions, username, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentSubmissionsRow
	for rows.Next() {
		var i GetUserRecentSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.ChallengeTitle,
			&i.Language,
			&i.Status,
			&i.RuntimeInfo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSolutions = `-- name: GetUserSolutions :many
SELECT id, user_id, challenge_id, code, language, status, runtime_info, created_at FROM solutions
WHERE user_id = ? AND challenge_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetUserSolutions(ctx context.Context, userID int64, challengeID int64) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getUserSolutions, userID, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.Code,
			&i.Language,
			&i.Status,
			&i.RuntimeInfo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
SELECT 
    u.username,
    u.created_at,
    u.is_admin,
    COUNT(DISTINCT ucc.challenge_id) as challenges_completed,
    COUNT(DISTINCT s.id) as total_solutions,
    COUNT(DISTINCT CASE WHEN s.status = 'accepted' THEN s.id END) as accepted_solutions,
    COUNT(DISTINCT CASE WHEN s.status = 'wrong_answer' THEN s.id END) as wrong_answers,
    COUNT(DISTINCT CASE WHEN s.status = 'runtime_error' THEN s.id END) as runtime_errors
FROM users u
LEFT JOIN user_completed_challenges ucc ON u.id = ucc.user_id
LEFT JOIN solutions s ON u.id = s.user_id
WHERE u.username = ?
GROUP BY u.id, u.username, u.created_at, u.is_admin
`

type GetUserStatsRow struct {
	Username            string `json:"username"`
	CreatedAt           int64  `json:"created_at"`
	IsAdmin             int64  `json:"is_admin"`
	ChallengesCompleted int64  `json:"challenges_completed"`
	TotalSolutions      int64  `json:"total_solutions"`
	AcceptedSolutions   int64  `json:"accepted_solutions"`
	WrongAnswers        int64  `json:"wrong_answers"`
	RuntimeErrors       int64  `json:"runtime_errors"`
}

func (q *Queries) GetUserStats(ctx context.Context, username string) (GetUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, username)
	var i GetUserStatsRow
	err := row.Scan(
		&i.Username,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.ChallengesCompleted,
		&i.TotalSolutions,
		&i.AcceptedSolutions,
		&i.WrongAnswers,
		&i.RuntimeErrors,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, password_hash, is_admin, created_at, updated_at FROM users ORDER BY username
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newChallenge = `-- name: NewChallenge :one
INSERT INTO challenges (title, description, difficulty)
VALUES (?, ?, ?)
RETURNING id
`

func (q *Queries) NewChallenge(ctx context.Context, title string, description string, difficulty int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, newChallenge, title, description, difficulty)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const newChallengeTest = `-- name: NewChallengeTest :one
INSERT INTO challenge_tests (challenge_id, input_data, expected_output)
VALUES (?, ?, ?)
RETURNING id
`

func (q *Queries) NewChallengeTest(ctx context.Context, challengeID int64, inputData string, expectedOutput string) (int64, error) {
	row := q.db.QueryRowContext(ctx, newChallengeTest, challengeID, inputData, expectedOutput)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const newSolution = `-- name: NewSolution :one
INSERT INTO solutions (user_id, challenge_id, code, language, status, runtime_info)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type NewSolutionParams struct {
	UserID      int64          `json:"user_id"`
	ChallengeID int64          `json:"challenge_id"`
	Code        string         `json:"code"`
	Language    string         `json:"language"`
	Status      string         `json:"status"`
	RuntimeInfo sql.NullString `json:"runtime_info"`
}

func (q *Queries) NewSolution(ctx context.Context, arg NewSolutionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, newSolution,
		arg.UserID,
		arg.ChallengeID,
		arg.Code,
		arg.Language,
		arg.Status,
		arg.RuntimeInfo,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const newUser = `-- name: NewUser :one
INSERT INTO users (username, password_hash) VALUES (?, ?) RETURNING id
`

func (q *Queries) NewUser(ctx context.Context, username string, passwordHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, newUser, username, passwordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSolutionStatus = `-- name: UpdateSolutionStatus :one
UPDATE solutions
SET status = ?1,
    runtime_info = ?2
WHERE id = ?3
RETURNING id, user_id, challenge_id, code, language, status, runtime_info, created_at
`

func (q *Queries) UpdateSolutionStatus(ctx context.Context, newstatus string, runtimeinfo sql.NullString, solutionid int64) (Solution, error) {
	row := q.db.QueryRowContext(ctx, updateSolutionStatus, newstatus, runtimeinfo, solutionid)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Code,
		&i.Language,
		&i.Status,
		&i.RuntimeInfo,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET
password_hash = ?1, updated_at = unixepoch()
WHERE id = ?2 RETURNING id, username, password_hash, is_admin, created_at, updated_at
`

func (q *Queries) UpdateUserPassword(ctx context.Context, newpassword []byte, userid int64) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, newpassword, userid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
