package main

import (
	"context"
	"flag"
	"log"
	"os"

	"lameCode/internal/platform/config"
	"lameCode/internal/platform/data"

	"github.com/gin-gonic/gin"
)

func main() {
	config.LoadServerFlags()
	flag.Parse()
	gin.SetMode(gin.ReleaseMode) // Gin itself is on release mode, not necessarily the app

	if config.Debug() {
		l.Println("Running LameCode on debug mode...")
	} else {
		l.Println("Running LameCode on release mode...")
	}

	// Apply schema if directed
	if config.ApplySchema() || config.DbUrl() == ":memory:" {
		l.Println("Applying schema...")
		err := data.LoadSchema(data.DB())
		if err != nil {
			l.Fatalln("Failed to apply schema:\n", err)
		}
	}

	// create autogenerated admin user to get started
	admins, err := data.Repository().GetUsersByStatus(context.Background(), 1)
	if err != nil {
		l.Fatalf("Could not check for existing admins in database...\n%v\n", err)
	}

	if len(admins) == 0 && !config.ApplySchema() {
		setupAdminUser()
	}
	
	r := gin.Default()

	loadRoutes(r) // router.go

	port := "3000" // Default port
	// Check for override of port
	if p := os.Getenv("PORT"); p != "" {
		port = p
	}
	
	if err := r.Run(":" + port); err != nil {
		log.Fatalln("Exited server with err:", err)
	}
}
