package main

import (
	"flag"
	"log"
	"os"

	"lameCode/internal/platform/config"
	"lameCode/internal/platform/data"

	"github.com/gin-gonic/gin"
)

var r *gin.Engine

func main() {
	config.LoadServerFlags()
	flag.Parse()
	gin.SetMode(gin.ReleaseMode)

	if config.Debug() {
		data.DB().Ping() // this initializes database connection 
	} else {
		l.Println("Running LameCode on release mode...")
	}

	// create autogenerated admin user to get started
	if config.ApplySchema() { // already created at this point (data.DB() did it)
		setupAdminUser()
	}
	
	r := gin.Default()

	loadRoutes(r) // router.go

	port := "3000" // Default port
	// Check for override of port
	if p := os.Getenv("PORT"); p != "" {
		port = p
	}
	err := r.Run(":" + port)
	log.Fatalln("Exited server with err:", err)
}
